"""Constants for report provenance wording and banned-word detection.

APPROVED_WORDING maps evidence-level labels to human-readable provenance
strings.  BANNED_WORDS lists terms that overstate confidence.
BANNED_WORDS_PATTERN is a pre-compiled regex for efficient scanning.
"""

from __future__ import annotations

import re

# Approved provenance strings keyed by evidence-level label.
# Each string deliberately avoids assurance language — these are
# factual descriptions of how the evidence was produced.
APPROVED_WORDING: dict[str, str] = {
    "requested": "Property was requested but has not yet been computed.",
    "generated": "Generated by a generative model; no independent validation performed.",
    "heuristic_estimated": "Estimated via heuristic rules; not experimentally verified.",
    "ml_predicted": "Predicted by a machine-learning surrogate; not experimentally verified.",
    "ml_relaxed": "Structure relaxed with an ML force field; not verified by higher-fidelity methods.",
    "semiempirical_qc": "Computed with a semiempirical quantum-chemistry method; accuracy is limited.",
    "dft_verified": "Verified by density-functional theory calculation.",
    "experimental_reported": "Based on experimental measurement.",
    "unknown": "Evidence level could not be determined; treat with caution.",
}

# Terms that overstate the confidence of computational results.
# Kept as a frozenset for O(1) membership checks in non-regex paths.
BANNED_WORDS: frozenset[str] = frozenset({
    "discovered",
    "proven",
    "guaranteed stable",
    "clinically relevant",
    "synthesizable",
    "optimal",
    "validated",
    "novel material",
})

# Pre-compiled regex for banned-word detection with word-boundary anchors.
# re.IGNORECASE so that "Proven" and "PROVEN" are caught.
# Built once at module level — not per request.
BANNED_WORDS_PATTERN: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(w) for w in sorted(BANNED_WORDS)) + r")\b",
    re.IGNORECASE,
)
